### ISSUE TITLE
Phase 0 Report

### ISSUE THREAD

**Issue by RozhTagh** [advanced-programming-sut-2023/project-group-10#1]
<div dir="rtl" align='right'>

# فاز 0

## کارهایی که باید در فاز 0 انجام دهید

<details>
  <summary>راه‌اندازی مخزن GItHub</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>راه‌اندازی GitHub Issue</summary>
  
  <div  dir="ltr" align='right'>
  
  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
     </div>
</details>

<details>
  <summary>طراحی UML برای منطق پروژه</summary>
  
  <div  dir="ltr" align='right'>
  
  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
     </div>
</details>

## تسک‌های نفر اول

  **نام و نام خانوادگی: یسنا نوشیروانی
<details>
  <summary>کامیت نام و شماره دانشجویی در README.md</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>طراحی کلاس‌های مربوط به نقشه و محیط بازی</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>طراحی کلاس بازی (Battle)</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>طراحی کلاس‌ های مربوط به افراد</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

<details>
  <summary>طراحی کلاس‌ های مربوط به siege equipment</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

## تسک‌های نفر دوم

  **نام و نام خانوادگی:روژین تقی زادگان
<details>
  <summary>کامیت نام و شماره دانشجویی در README.md</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
<summary>ساخت کلاس های مربوط به ساختمان</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
<summary>ساخت منو و کنترلر لاگین</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
<summary>ساخت منو و کنترلر  پروفایل</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>

## تسک‌های نفر سوم

  **نام و نام خانوادگی: مهرآذین ملک قاسمی
<details>
  <summary>کامیت نام و شماره دانشجویی در README.md </summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>ساخت کلاس user </summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>ساخت کلاس government </summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>هندل کردن ایتم ها</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>
  <summary>کنترلر و ویو register menu</summary>
  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>

</details>
<details>
  <summary>trade & shop</summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
<details>

  <summary>گیم منو </summary>

  <div dir="ltr" align='right'>

  1. [ ] شروع نشده
  2. [ ] در حال انجام
  3. [x] تمام شده
  </div>
</details>
</div>

**Comment by MehrazinM** [comment]
phase 0 finished
